## Numpy 
Creating Arrays and performing operations

In [2]:
!pip install numpy
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 12.3 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.6 MB 11.9 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 11.9 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 11.1 MB/s  0:00:01


array([10, 20, 30, 40, 50])

In [7]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(5,)
1
int64


## Indexing and Slicing

In [9]:
arr[0]


np.int64(10)

In [10]:
arr[1:4]

array([20, 30, 40])

In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix.shape

(3, 3)

In [13]:
matrix[0]

array([1, 2, 3])

In [ ]:
matrix[:, 1] #matrix[rows, columns]- all rows, column index 1

array([2, 5, 8])

## Vectorised Operations

In [15]:
arr * 2

array([ 20,  40,  60,  80, 100])

In [16]:
arr + 10

array([20, 30, 40, 50, 60])

In [17]:
arr ** 2

array([ 100,  400,  900, 1600, 2500])

## Aggregation

In [18]:
arr.sum()

np.int64(150)

In [19]:
arr.mean()

np.float64(30.0)

In [20]:
arr.min()

np.int64(10)

In [21]:
arr.max()

np.int64(50)

In [22]:
arr.std()

np.float64(14.142135623730951)

## Filtering

In [23]:
arr[arr > 25]

array([30, 40, 50])

## Reshaping

In [24]:
numbers = np.arange(1, 13)
matrix = numbers.reshape(3, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
matrix.shape

(3, 4)